-- Creating the warehouse --
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;

-- Selecting the warehouse --
USE WAREHOUSE VP_WAREHOUSE;

-- Creating the database --
CREATE DATABASE IF NOT EXISTS VP_LEADS;

-- Selecting the database --
USE VP_LEADS;

-- Creating the table COMPANYLEADS under the default schema PUBLIC --
CREATE TABLE IF NOT EXISTS COMPANYLEADS (
  ID VARCHAR(40) PRIMARY KEY, 
  STATE INTEGER,
  CREATED_DATE_UTC TIMESTAMP, 
  CANCELLATION_REQUEST_DATE_UTC TIMESTAMP, 
  CANCELLATION_DATE_UTC TIMESTAMP, 
  CANCELLATION_REJECTION_DATE_UTC TIMESTAMP, 
  UNDO_CANCELLATION_DATE_UTC TIMESTAMP, 
  CANCELED_EMPLOYEE VARCHAR(255), 
  SOLD_EMPLOYEE VARCHAR(255), 
  UPDATED_DATE_UTC TIMESTAMP
);

-- Creating the table LEADEVENTS under the default schema PUBLIC --
CREATE TABLE IF NOT EXISTS LEADEVENTS (
  ID VARCHAR(40) PRIMARY KEY,
  EVENT_TYPE VARCHAR(50),
  EVENT_EMPLOYEE VARCHAR(255),
  EVENT_DATE TIMESTAMP,
  LEAD_ID VARCHAR(40),
  UPDATED_DATE_UTC TIMESTAMP
);